In [1]:
# prompt: mount google drive

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

# DataFrame 생성

In [3]:
# Dictionary
a1 = pd.DataFrame({"a":[1,2,3], "b":[4,5,6], "c":[7,8,9]})
a1

   a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [4]:
# List
a2 = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9]], columns=["a", "b", "c"])
a2

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [5]:
# csv
%cd /content/drive/MyDrive/Colab Notebooks/github_python_ML/KT_AICE/AICE_source

/content/drive/MyDrive/Colab Notebooks/github_python_ML/KT_AICE/AICE_source

In [6]:
a3 = pd.read_csv("Clean_Dataset.csv")
a3

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

# DataFrame 데이터 살펴보기

In [7]:
# head & tail
# 데이터 전체가 아닌, 일부를 간단히 보기 위한 함수(default; 5줄)
# 데이터의 자료형 확인, 각 레이블에 맞는 데이터 매칭 확인 목적!

a3.head()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [8]:
a3.tail(n=3)

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [9]:
# shape

a3.shape

(300153, 12)

In [10]:
# columns

a3.columns

Index(['Unnamed: 0', 'airline', 'flight', 'source_city', 'departure_time',
       'stops', 'arrival_time', 'destination_city', 'class', 'duration',
       'days_left', 'price'],
      dtype='object')

In [11]:
# index = 몇 개의 행이 있는지 보여주는듯

a3.index

RangeIndex(start=0, stop=300153, step=1)

In [12]:
# index.values = 실제 행 구성이 어떻게 되는지 표시
# 아~ 0번부터 300152번까지 있구나

a3.index.values

array([     0,      1,      2, ..., 300150, 300151, 300152])

In [13]:
# values
# numpy array로 보여줌

a3.values

array([[0, 'SpiceJet', 'SG-8709', ..., 2.17, 1, 5953],
       [1, 'SpiceJet', 'SG-8157', ..., 2.33, 1, 5953],
       [2, 'AirAsia', 'I5-764', ..., 2.17, 1, 5956],
       ...,
       [300150, 'Vistara', 'UK-832', ..., 13.83, 49, 79099],
       [300151, 'Vistara', 'UK-828', ..., 10.0, 49, 81585],
       [300152, 'Vistara', 'UK-822', ..., 10.08, 49, 81585]], dtype=object)

In [14]:
# info
# 각 컬럼에 대한 정보 표시
# Dtype: object == 문자열이라는 뜻

a3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        300153 non-null  int64
 1   airline           300153 non-null  object
 2   flight            300153 non-null  object
 3   source_city       300153 non-null  object
 4   departure_time    300153 non-null  object
 5   stops             300153 non-null  object
 6   arrival_time      300153 non-null  object
 7   destination_city  300153 non-null  object
 8   class             300153 non-null  object
 9   duration          300153 non-null  float64
 10  days_left         300153 non-null  int64
 11  price             300153 non-null  int64
dtypes: float64(1), int64(3), object(8)
memory usage: 27.5+ MB

In [15]:
# dtypes
# info()랑 비슷한데, 컬럼의 타입만을 보여주는 것

a3.dtypes

Unnamed: 0            int64
airline              object
flight               object
source_city          object
departure_time       object
stops                object
arrival_time         object
destination_city     object
class                object
duration            float64
days_left             int64
price                 int64
dtype: object

In [16]:
# describe

a3.describe()

          Unnamed: 0       duration      days_left          price
count  300153.000000  300153.000000  300153.000000  300153.000000
mean   150076.000000      12.221021      26.004751   20889.660523
std     86646.852011       7.191997      13.561004   22697.767366
min         0.000000       0.830000       1.000000    1105.000000
25%     75038.000000       6.830000      15.000000    4783.000000
50%    150076.000000      11.250000      26.000000    7425.000000
75%    225114.000000      16.170000      38.000000   42521.000000
max    300152.000000      49.830000      49.000000  123071.000000

## 하나의 컬럼 선택하기

In [17]:
# cf. series 형태로 가져오기(a3.a3_class = a3["price"])

a3["price"]

0          5953
1          5953
2          5956
3          5955
4          5955
          ...
300148    69265
300149    77105
300150    79099
300151    81585
300152    81585
Name: price, Length: 300153, dtype: int64

In [19]:
a3.a3_class = a3["price"]

# series 형태로 가져오기
a3.a3_class

0          5953
1          5953
2          5956
3          5955
4          5955
          ...
300148    69265
300149    77105
300150    79099
300151    81585
300152    81585
Name: price, Length: 300153, dtype: int64

In [20]:
# DataFrame 형태로 가져오기
# 인덱스(숫자)로 가져오면 키 에러 남 - 아래쪽 설명 참고!
a3[ ["price"] ]

        price
0        5953
1        5953
2        5956
3        5955
4        5955
...       ...
300148  69265
300149  77105
300150  79099
300151  81585
300152  81585

[300153 rows x 1 columns]

## 복수의 컬럼 선택하기

In [21]:
# 여러 개의 요소를 선택 시 리스트를 사용하여 표시

a3[ ["price", "duration", "destination_city"] ]

        price  duration destination_city
0        5953      2.17           Mumbai
1        5953      2.33           Mumbai
2        5956      2.17           Mumbai
3        5955      2.25           Mumbai
4        5955      2.33           Mumbai
...       ...       ...              ...
300148  69265     10.08        Hyderabad
300149  77105     10.42        Hyderabad
300150  79099     13.83        Hyderabad
300151  81585     10.00        Hyderabad
300152  81585     10.08        Hyderabad

[300153 rows x 3 columns]

## 슬라이싱
- 특정 행 범위를 가지고 오고 싶다면 [ ]를 사용
- e.g. 7~10행 가져오고 싶다면 cust[ 7:10 ]

In [22]:
a3[ 7:10 ]

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
7,7,Vistara,UK-951,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.17,1,6060
8,8,GO_FIRST,G8-334,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.17,1,5954
9,9,GO_FIRST,G8-336,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.25,1,5954

- [주의] 데이터프레임에 대해 인덱스로 접근 시 에러 발생
* 기본적으로 데이터프레임은 인덱스 접근 시 컬럼명 접근으로 설계되어, 인덱스 번호 "숫자"는 컬럼명에 없으므로 에러 발생

In [23]:
a3[7] # 키 에러 발생

KeyError: 7

## 로우 선택하기

- loc: 데이터프레임에 존재하는 인덱스를 그대로 사용(인덱스 기준으로 행 데이터 읽기)
- iloc: 데이터프레임에 존재하는 인덱스 상관 없이 **0 based index**로 사용(행 번호 기준으로 행 데이터 읽기)

In [25]:
a3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        300153 non-null  int64
 1   airline           300153 non-null  object
 2   flight            300153 non-null  object
 3   source_city       300153 non-null  object
 4   departure_time    300153 non-null  object
 5   stops             300153 non-null  object
 6   arrival_time      300153 non-null  object
 7   destination_city  300153 non-null  object
 8   class             300153 non-null  object
 9   duration          300153 non-null  float64
 10  days_left         300153 non-null  int64
 11  price             300153 non-null  int64
dtypes: float64(1), int64(3), object(8)
memory usage: 27.5+ MB

In [26]:
# a3의 기존 인덱스 확인
a3.index

RangeIndex(start=0, stop=300153, step=1)

In [27]:
# np.arange 함수 활용해서 a3의 인덱스를 100번부터 시작하도록 강제로 수정
a3.index = np.arange(100, 300253)
a3.index

Index([   100,    101,    102,    103,    104,    105,    106,    107,    108,
          109,
       ...
       300243, 300244, 300245, 300246, 300247, 300248, 300249, 300250, 300251,
       300252],
      dtype='int64', length=300153)

In [28]:
# 인덱스가 100번부터 시작하는 것 잘 확인함
a3.head()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
100,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
101,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
102,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
103,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
104,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [30]:
a3.tail()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
300248,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300249,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300250,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300251,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300252,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [31]:
# ㅣoc: 데이터프레임에 존재하는 인덱스를 그대로 사용(인덱스 기준으로 행 데이터 읽기)
a3.loc[ 300251 ]

Unnamed: 0                 300151
airline                   Vistara
flight                     UK-828
source_city               Chennai
departure_time      Early_Morning
stops                         one
arrival_time              Evening
destination_city        Hyderabad
class                    Business
duration                     10.0
days_left                      49
price                       81585
Name: 300251, dtype: object

In [35]:
# 데이터프레임 형식으로 읽어보기 - 리스트 형태로 row 여러개 포함할 수 있음
a3.loc[ [300251, 300252] ]

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
300251,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300252,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [37]:
# iloc: 데이터프레임에 존재하는 인덱스 상관 없이 0 based index로 사용(행 번호 기준으로 행 데이터 읽기)
a3.iloc[ 0 ]

Unnamed: 0                 0
airline             SpiceJet
flight               SG-8709
source_city            Delhi
departure_time       Evening
stops                   zero
arrival_time           Night
destination_city      Mumbai
class                Economy
duration                2.17
days_left                  1
price                   5953
Name: 100, dtype: object

- row, column 동시에 선택하기
    - loc, iloc 속성을 이용할 때, 콤마를 이용하여 row와 col 다 명시 가능

In [42]:
# 102 인덱스의 price 컬럼값 가져오기
a3.loc[ 102, 'price' ]

5956

In [43]:
# loc 함수를 활용해 102, 202, 302 인덱스의 airline, source_city, destination_city, price 가져오기
a3.loc[ [102, 202, 302], ['airline', 'source_city', 'destination_city', 'price'] ]

     airline source_city destination_city  price
102  AirAsia       Delhi           Mumbai   5956
202  Vistara       Delhi           Mumbai  18923
302  Vistara       Delhi           Mumbai  13673

In [45]:
# iloc 함수를 활용해 2, 102, 202 인덱스의 airline, source_city, destination_city, price 가져오기
# iloc 함수의 경우 인덱스와 컬럼들의 절대적 위치로 표현하는걸 알 수 있다.

a3.iloc[ [2, 102, 202], [0, 3, 4, 11] ]

     Unnamed: 0 source_city departure_time  price
102           2       Delhi  Early_Morning   5956
202         102       Delhi      Afternoon  18923
302         202       Delhi        Evening  13673

## Boolean Indexing으로 Row 선택하기
- 해당 조건에 맞는 row만 선택
- 2개 이상의 조건 묶을 때 AND나 OR을 사용할 수 있음 / &, | 기호로만 사용함

> e.g. source_city가 Delhi 이면서 Duration이 5 이상 8 미만인 항공편만 가져오기

In [ ]:
# 조건 분해
# 1. soource_city = Delhi
# 2. Duration 5 이상 7 이하

In [46]:
# 1. soource_city = Delhi
a3["source_city"].head()

100    Delhi
101    Delhi
102    Delhi
103    Delhi
104    Delhi
Name: source_city, dtype: object

In [47]:
a3["source_city"] == "Delhi"

100        True
101        True
102        True
103        True
104        True
          ...
300248    False
300249    False
300250    False
300251    False
300252    False
Name: source_city, Length: 300153, dtype: bool

In [48]:
a3 [ a3["source_city"] == "Delhi" ]

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
100,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
101,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
102,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
103,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
104,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...,...
225077,224977,Vistara,UK-955,Delhi,Evening,one,Morning,Chennai,Business,15.08,49,68184
225078,224978,Air_India,AI-883,Delhi,Night,two_or_more,Morning,Chennai,Business,12.92,49,70323
225079,224979,Vistara,UK-829,Delhi,Early_Morning,two_or_more,Evening,Chennai,Business,12.83,49,71376
225080,224980,Vistara,UK-819,Delhi,Afternoon,two_or_more,Night,Chennai,Business,8.83,49,76684
225081,224981,Vistara,UK-705,Delhi,Early_Morning,two_or_more,Evening,Chennai,Business,12.42,49,82553

In [49]:
# 2. Duration 평균 5 이상 7 이하
a3["duration"].head()

100    2.17
101    2.33
102    2.17
103    2.25
104    2.33
Name: duration, dtype: float64

In [53]:
a3[ (a3["duration"] >= 5) & (a3["duration"] <= 7) ]

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
127,27,AirAsia,I5-744,Delhi,Morning,one,Afternoon,Mumbai,Economy,5.83,1,8869
131,31,Indigo,6E-2373,Delhi,Afternoon,one,Evening,Mumbai,Economy,6.00,1,10838
161,61,Vistara,UK-747,Delhi,Early_Morning,one,Afternoon,Mumbai,Economy,6.50,1,13935
181,81,Indigo,6E-2102,Delhi,Early_Morning,one,Afternoon,Mumbai,Economy,5.08,1,15720
188,88,Vistara,UK-817,Delhi,Evening,one,Night,Mumbai,Economy,5.75,1,17348
...,...,...,...,...,...,...,...,...,...,...,...,...
300171,300071,Air_India,AI-672,Chennai,Afternoon,one,Night,Hyderabad,Business,5.83,48,40593
300174,300074,Vistara,UK-828,Chennai,Early_Morning,one,Afternoon,Hyderabad,Business,5.25,48,41064
300193,300093,Air_India,AI-539,Chennai,Evening,one,Night,Hyderabad,Business,6.58,48,51345
300215,300115,Vistara,UK-828,Chennai,Early_Morning,one,Afternoon,Hyderabad,Business,5.25,49,41064
300240,300140,Air_India,AI-539,Chennai,Evening,one,Night,Hyderabad,Business,6.58,49,51345

In [55]:
# 최종: source_city가 Delhi 이면서 Duration이 5 이상 7 이하인 항공편만 가져오기
a3[ (a3["source_city"] == "Delhi") & (a3["duration"] >= 5) & (a3["duration"] <= 7) ]

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
127,27,AirAsia,I5-744,Delhi,Morning,one,Afternoon,Mumbai,Economy,5.83,1,8869
131,31,Indigo,6E-2373,Delhi,Afternoon,one,Evening,Mumbai,Economy,6.00,1,10838
161,61,Vistara,UK-747,Delhi,Early_Morning,one,Afternoon,Mumbai,Economy,6.50,1,13935
181,81,Indigo,6E-2102,Delhi,Early_Morning,one,Afternoon,Mumbai,Economy,5.08,1,15720
188,88,Vistara,UK-817,Delhi,Evening,one,Night,Mumbai,Economy,5.75,1,17348
...,...,...,...,...,...,...,...,...,...,...,...,...
224997,224897,Vistara,UK-955,Delhi,Evening,one,Night,Chennai,Business,5.33,48,60232
225037,224937,Vistara,UK-951,Delhi,Afternoon,one,Evening,Chennai,Business,5.58,49,45672
225051,224951,Vistara,UK-941,Delhi,Evening,one,Night,Chennai,Business,6.33,49,53512
225053,224953,Vistara,UK-975,Delhi,Early_Morning,one,Morning,Chennai,Business,5.83,49,57992
225076,224976,Vistara,UK-955,Delhi,Evening,one,Night,Chennai,Business,5.33,49,68184

In [56]:
# 조건문이 길어지면 변수화 해서 사용 가능
source_city = (a3["source_city"] == "Delhi")
duration = (a3["duration"] >= 5) & (a3["duration"] <= 7)

a3[ source_city & duration ]

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
127,27,AirAsia,I5-744,Delhi,Morning,one,Afternoon,Mumbai,Economy,5.83,1,8869
131,31,Indigo,6E-2373,Delhi,Afternoon,one,Evening,Mumbai,Economy,6.00,1,10838
161,61,Vistara,UK-747,Delhi,Early_Morning,one,Afternoon,Mumbai,Economy,6.50,1,13935
181,81,Indigo,6E-2102,Delhi,Early_Morning,one,Afternoon,Mumbai,Economy,5.08,1,15720
188,88,Vistara,UK-817,Delhi,Evening,one,Night,Mumbai,Economy,5.75,1,17348
...,...,...,...,...,...,...,...,...,...,...,...,...
224997,224897,Vistara,UK-955,Delhi,Evening,one,Night,Chennai,Business,5.33,48,60232
225037,224937,Vistara,UK-951,Delhi,Afternoon,one,Evening,Chennai,Business,5.58,49,45672
225051,224951,Vistara,UK-941,Delhi,Evening,one,Night,Chennai,Business,6.33,49,53512
225053,224953,Vistara,UK-975,Delhi,Early_Morning,one,Morning,Chennai,Business,5.83,49,57992
225076,224976,Vistara,UK-955,Delhi,Evening,one,Night,Chennai,Business,5.33,49,68184