In [1]:
# prompt: mount google drive

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [3]:
# csv
%cd /content/drive/MyDrive/Colab Notebooks/github_python_ML/KT_AICE/AICE_source

/content/drive/MyDrive/Colab Notebooks/github_python_ML/KT_AICE/AICE_source

# DataFrame 변형하기

## Groupby
- 데이터 분할(split)
- 적용(applying)
- 데이터 병합(combine)

```dataframe.gropuby('성별').mean()``` <- 성별 별로 평균값 구하기

### 1-1. 데이터 읽기

In [4]:
sample = pd.read_csv("Clean_Dataset.csv")
sample

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

### 1-2. 그룹화 하기

In [5]:
airline_group = sample.groupby('airline')
airline_group

In [6]:
# 그룹별로 묶였는지 확인: groups
airline_group.groups

{'AirAsia': [2, 18, 19, 27, 48, 141, 147, 148, 157, 265, 290, 325, 435, 450, 608, 609, 623, 706, 746, 782, 783, 784, 814, 978, 993, 1085, 1088, 1133, 1210, 1248, 1261, 1284, 1323, 1341, 1343, 1461, 1466, 1483, 1526, 1583, 1685, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1728, 1759, 1760, 1761, 1762, 1866, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1947, 1972, 1974, 1976, 1977, 1991, 1992, 2083, 2127, 2128, 2129, 2130, 2131, 2132, 2133, 2134, 2135, 2167, 2194, 2196, 2264, 2265, 2292, 2305, 2350, 2351, 2352, 2353, 2354, 2355, 2397, 2422, 2423, 2443, 2444, 2465, 2484, ...], 'Air_India': [16, 17, 23, 37, 40, 41, 42, 43, 44, 49, 50, 51, 52, 53, 60, 71, 74, 75, 82, 86, 87, 96, 98, 107, 108, 110, 113, 114, 115, 117, 142, 143, 144, 145, 146, 151, 152, 162, 163, 164, 166, 168, 173, 182, 189, 191, 193, 195, 196, 197, 198, 199, 207, 211, 223, 225, 229, 236, 237, 241, 242, 243, 247, 250, 266, 267, 268, 269, 272, 280, 291, 295, 303, 309, 314, 315, 316, 319, 321, 329, 333, 343, 352, 357, 361, 362, 363, 372, 376, 379, 380, 381, 385, 387, 388, 390, 391, 392, 393, 394, ...], 'GO_FIRST': [8, 9, 10, 11, 20, 21, 22, 30, 68, 72, 101, 112, 126, 127, 128, 129, 130, 131, 149, 150, 200, 201, 208, 212, 213, 222, 232, 235, 244, 245, 257, 258, 259, 260, 270, 271, 277, 278, 281, 296, 312, 313, 317, 327, 328, 342, 366, 368, 371, 384, 389, 413, 414, 415, 416, 417, 418, 436, 437, 438, 439, 440, 441, 442, 455, 465, 469, 490, 491, 496, 497, 535, 552, 586, 587, 588, 589, 590, 591, 610, 611, 612, 613, 614, 615, 616, 617, 627, 639, 640, 646, 668, 669, 672, 673, 675, 691, 762, 763, 764, ...], 'Indigo': [12, 13, 14, 15, 24, 26, 29, 31, 54, 55, 56, 57, 58, 67, 79, 81, 132, 133, 134, 135, 136, 137, 139, 140, 158, 159, 167, 170, 171, 172, 174, 175, 180, 181, 190, 224, 226, 228, 261, 262, 263, 264, 282, 283, 284, 285, 286, 287, 292, 297, 301, 302, 307, 308, 310, 323, 324, 332, 337, 348, 353, 354, 358, 359, 360, 419, 420, 421, 422, 424, 425, 426, 427, 428, 445, 446, 447, 451, 454, 456, 457, 458, 459, 466, 479, 488, 489, 522, 524, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 625, ...], 'SpiceJet': [0, 1, 28, 38, 39, 45, 80, 118, 119, 138, 160, 161, 194, 227, 251, 252, 253, 274, 275, 294, 306, 311, 331, 398, 399, 400, 401, 402, 403, 423, 444, 448, 449, 452, 520, 540, 563, 564, 565, 566, 567, 568, 569, 570, 619, 620, 621, 622, 624, 665, 738, 739, 740, 741, 742, 743, 744, 745, 799, 800, 802, 844, 877, 898, 919, 920, 921, 922, 923, 924, 925, 971, 974, 975, 1049, 1092, 1104, 1105, 1106, 1107, 1108, 1109, 1110, 1111, 1150, 1155, 1200, 1243, 1281, 1286, 1287, 1288, 1289, 1290, 1291, 1331, 1332, 1368, 1369, 1412, ...], 'Vistara': [3, 4, 5, 6, 7, 25, 32, 33, 34, 35, 36, 46, 47, 59, 61, 62, 63, 64, 65, 66, 69, 70, 73, 76, 77, 78, 83, 84, 85, 88, 89, 90, 91, 92, 93, 94, 95, 97, 99, 100, 102, 103, 104, 105, 106, 109, 111, 116, 120, 121, 122, 123, 124, 125, 153, 154, 155, 156, 165, 169, 176, 177, 178, 179, 183, 184, 185, 186, 187, 188, 192, 202, 203, 204, 205, 206, 209, 210, 214, 215, 216, 217, 218, 219, 220, 221, 230, 231, 233, 234, 238, 239, 240, 246, 248, 249, 254, 255, 256, 273, ...]}

### 1-3. groupby 내부 함수 활용하기
- count
- size: 집단별 크기
- sum
- mean, std, var
- min, max

In [7]:
airline_group.count()

,Unnamed: 0,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
airline,,,,,,,,,,,
AirAsia,16098,16098,16098,16098,16098,16098,16098,16098,16098,16098,16098
Air_India,80892,80892,80892,80892,80892,80892,80892,80892,80892,80892,80892
GO_FIRST,23173,23173,23173,23173,23173,23173,23173,23173,23173,23173,23173
Indigo,43120,43120,43120,43120,43120,43120,43120,43120,43120,43120,43120
SpiceJet,9011,9011,9011,9011,9011,9011,9011,9011,9011,9011,9011
Vistara,127859,127859,127859,127859,127859,127859,127859,127859,127859,127859,127859

In [8]:
airline_group.size()

airline
AirAsia       16098
Air_India     80892
GO_FIRST      23173
Indigo        43120
SpiceJet       9011
Vistara      127859
dtype: int64

In [9]:
# 범주형 자료에 문자가 포함될 경우 에러 발생할 수 있음
airline_group.mean()

TypeError: agg function failed [how->mean,dtype->object]

In [10]:
# 숫자 타입의 컬럼들만 선택
numeric_columns = sample.select_dtypes(include='number').columns

# 그룹바이 후 해당 컬럼들에 대해서만 평균 계산
result = sample.groupby('airline')[numeric_columns].mean()
result

              Unnamed: 0   duration  days_left         price
airline
AirAsia     95102.971922   8.941714  27.735184   4091.072742
Air_India  162945.107007  15.504235  25.497466  23507.019112
GO_FIRST    87630.797005   8.755380  27.430415   5652.007595
Indigo     110102.972658   5.795197  26.264309   5324.216303
SpiceJet    91878.408834  12.579767  24.122850   6179.278881
Vistara    177755.288310  13.326634  25.894532  30396.536302

In [11]:
sample.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        300153 non-null  int64
 1   airline           300153 non-null  object
 2   flight            300153 non-null  object
 3   source_city       300153 non-null  object
 4   departure_time    300153 non-null  object
 5   stops             300153 non-null  object
 6   arrival_time      300153 non-null  object
 7   destination_city  300153 non-null  object
 8   class             300153 non-null  object
 9   duration          300153 non-null  float64
 10  days_left         300153 non-null  int64
 11  price             300153 non-null  int64
dtypes: float64(1), int64(3), object(8)
memory usage: 27.5+ MB

In [12]:
# 아니면 아렇게 숫자형 컬러만 수동으로 찾아서 처리
airline_group[ ['price', 'days_left', 'duration' ] ].mean()

                  price  days_left   duration
airline
AirAsia     4091.072742  27.735184   8.941714
Air_India  23507.019112  25.497466  15.504235
GO_FIRST    5652.007595  27.430415   8.755380
Indigo      5324.216303  26.264309   5.795197
SpiceJet    6179.278881  24.122850  12.579767
Vistara    30396.536302  25.894532  13.326634

In [13]:
airline_group['price'].max()
airline_group.max()['price'] # 똑같음

airline
AirAsia       31917
Air_India     90970
GO_FIRST      32803
Indigo        31952
SpiceJet      34158
Vistara      123071
Name: price, dtype: int64

In [14]:
# 위 절차 총정리
sample.groupby('airline')[ ['price', 'days_left', 'duration' ] ].mean()

                  price  days_left   duration
airline
AirAsia     4091.072742  27.735184   8.941714
Air_India  23507.019112  25.497466  15.504235
GO_FIRST    5652.007595  27.430415   8.755380
Indigo      5324.216303  26.264309   5.795197
SpiceJet    6179.278881  24.122850  12.579767
Vistara    30396.536302  25.894532  13.326634

### 1-4. 그룹화 하기(여러 개)

In [15]:
# airline, source_city 별로 그룹화해서 price 평균 구하기
sample.groupby( ['airline', 'source_city'] )['price'].mean()

# 변수화 해서도 가능함
multi_group = sample.groupby( ['airline', 'source_city'] )
multi_group['price'].mean()

airline    source_city
AirAsia    Bangalore       4222.787158
           Chennai         3243.964619
           Delhi           4514.854798
           Hyderabad       3359.273319
           Kolkata         4504.940615
           Mumbai          3698.312960
Air_India  Bangalore      24874.431796
           Chennai        25415.500908
           Delhi          21899.890758
           Hyderabad      22458.063853
           Kolkata        25233.867742
           Mumbai         22540.778419
GO_FIRST   Bangalore       5492.290574
           Chennai         5403.972847
           Delhi           5742.409679
           Hyderabad       4958.293131
           Kolkata         6638.820334
           Mumbai          5421.236351
Indigo     Bangalore       5230.785311
           Chennai         4827.233916
           Delhi           5386.570134
           Hyderabad       4774.240708
           Kolkata         6223.829221
           Mumbai          5371.185985
SpiceJet   Bangalore       6184.534661
           Chennai         5401.044299
           Delhi           6084.649762
           Hyderabad       6189.731928
           Kolkata         6852.890601
           Mumbai          6101.956747
Vistara    Bangalore      30834.436629
           Chennai        30401.842703
           Delhi          28938.500342
           Hyderabad      27791.447325
           Kolkata        32794.276565
           Mumbai         31522.101390
Name: price, dtype: float64

In [16]:
# 멀티인덱스에서 loc 함수를 사용하여 원하는 row 선택하기

sample.groupby( ['airline', 'source_city'] )['price'].mean().loc[ [('SpiceJet', 'Delhi'), ('Vistara', 'Delhi')] ]

airline   source_city
SpiceJet  Delhi           6084.649762
Vistara   Delhi          28938.500342
Name: price, dtype: float64

### 1-5. index를 이용한 groupby
- set_index: column 데이터를 index 레벨로 변경할 때 사용
- reset_index: 0부터 시작하는 새로운 인덱스 생성하여 인덱스 초기화

In [17]:
sample.head()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [19]:
sample.drop('Unnamed: 0', axis=1, inplace=True) #위에서 확인한대로 불필요한 컬럼은 그냥 제거함(강의에 없는 내용이고 내가 판단해서 지우는 것임)

In [20]:
# sample에서 arrival_time을 인덱스로 만들어 보기

sample.set_index('arrival_time')

,airline,flight,source_city,departure_time,stops,destination_city,class,duration,days_left,price
arrival_time,,,,,,,,,,
Night,SpiceJet,SG-8709,Delhi,Evening,zero,Mumbai,Economy,2.17,1,5953
Morning,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Mumbai,Economy,2.33,1,5953
Early_Morning,AirAsia,I5-764,Delhi,Early_Morning,zero,Mumbai,Economy,2.17,1,5956
Afternoon,Vistara,UK-995,Delhi,Morning,zero,Mumbai,Economy,2.25,1,5955
Morning,Vistara,UK-963,Delhi,Morning,zero,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...
Evening,Vistara,UK-822,Chennai,Morning,one,Hyderabad,Business,10.08,49,69265
Night,Vistara,UK-826,Chennai,Afternoon,one,Hyderabad,Business,10.42,49,77105
Night,Vistara,UK-832,Chennai,Early_Morning,one,Hyderabad,Business,13.83,49,79099
Evening,Vistara,UK-828,Chennai,Early_Morning,one,Hyderabad,Business,10.00,49,81585
Evening,Vistara,UK-822,Chennai,Morning,one,Hyderabad,Business,10.08,49,81585

In [22]:
# 여러 컬럼을 인덱스로 만들어 보기

multi_sample = sample.set_index(['airline', 'source_city'])
multi_sample

                       flight departure_time stops   arrival_time  \
airline  source_city
SpiceJet Delhi        SG-8709        Evening  zero          Night
         Delhi        SG-8157  Early_Morning  zero        Morning
AirAsia  Delhi         I5-764  Early_Morning  zero  Early_Morning
Vistara  Delhi         UK-995        Morning  zero      Afternoon
         Delhi         UK-963        Morning  zero        Morning
...                       ...            ...   ...            ...
         Chennai       UK-822        Morning   one        Evening
         Chennai       UK-826      Afternoon   one          Night
         Chennai       UK-832  Early_Morning   one          Night
         Chennai       UK-828  Early_Morning   one        Evening
         Chennai       UK-822        Morning   one        Evening

                     destination_city     class  duration  days_left  price
airline  source_city
SpiceJet Delhi                 Mumbai   Economy      2.17          1   5953
         Delhi                 Mumbai   Economy      2.33          1   5953
AirAsia  Delhi                 Mumbai   Economy      2.17          1   5956
Vistara  Delhi                 Mumbai   Economy      2.25          1   5955
         Delhi                 Mumbai   Economy      2.33          1   5955
...                               ...       ...       ...        ...    ...
         Chennai            Hyderabad  Business     10.08         49  69265
         Chennai            Hyderabad  Business     10.42         49  77105
         Chennai            Hyderabad  Business     13.83         49  79099
         Chennai            Hyderabad  Business     10.00         49  81585
         Chennai            Hyderabad  Business     10.08         49  81585

[300153 rows x 9 columns]

In [23]:
# reset_index 활용: 기존의 인덱스를 버리고, 새로운 0번부터 인덱스 지정 (set_index <-> reset_index)
multi_sample.reset_index() #단순 출력만 함. 저장되는건 아님

,airline,source_city,flight,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,SpiceJet,Delhi,SG-8709,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,SpiceJet,Delhi,SG-8157,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,AirAsia,Delhi,I5-764,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,Vistara,Delhi,UK-995,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,Vistara,Delhi,UK-963,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...
300148,Vistara,Chennai,UK-822,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,Vistara,Chennai,UK-826,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,Vistara,Chennai,UK-832,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,Vistara,Chennai,UK-828,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,Vistara,Chennai,UK-822,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [24]:
multi_sample.head(3)

                       flight departure_time stops   arrival_time  \
airline  source_city
SpiceJet Delhi        SG-8709        Evening  zero          Night
         Delhi        SG-8157  Early_Morning  zero        Morning
AirAsia  Delhi         I5-764  Early_Morning  zero  Early_Morning

                     destination_city    class  duration  days_left  price
airline  source_city
SpiceJet Delhi                 Mumbai  Economy      2.17          1   5953
         Delhi                 Mumbai  Economy      2.33          1   5953
AirAsia  Delhi                 Mumbai  Economy      2.17          1   5956

In [27]:
# multi_sample 데이터프레임에서 airline으로 그룹핑 해보기

multi_sample.groupby('airline').count()['flight']

airline
AirAsia       16098
Air_India     80892
GO_FIRST      23173
Indigo        43120
SpiceJet       9011
Vistara      127859
Name: flight, dtype: int64

In [28]:
# multi_sample 데이터프레임에서 source_city로 그룹핑 해보기
multi_sample.groupby('source_city').count()['flight']

source_city
Bangalore    52061
Chennai      38700
Delhi        61343
Hyderabad    40806
Kolkata      46347
Mumbai       60896
Name: flight, dtype: int64

In [30]:
# 아래처럼도 할 수 있음
# set_index를 통해 인덱스를 만들고, 그룹핑해서 보기

sample.set_index(['airline', 'source_city']).groupby(['airline', 'source_city']).count().head()

                     flight  departure_time  stops  arrival_time  \
airline source_city
AirAsia Bangalore      3364            3364   3364          3364
        Chennai        1498            1498   1498          1498
        Delhi          4387            4387   4387          4387
        Hyderabad      1844            1844   1844          1844
        Kolkata        2829            2829   2829          2829

                     destination_city  class  duration  days_left  price
airline source_city
AirAsia Bangalore                3364   3364      3364       3364   3364
        Chennai                  1498   1498      1498       1498   1498
        Delhi                    4387   4387      4387       4387   4387
        Hyderabad                1844   1844      1844       1844   1844
        Kolkata                  2829   2829      2829       2829   2829

### 1-6. aggregate(집계) 함수 사용하기
- groupby 결과에 집계함수를 적용하여 그룹별 데이터 확인 가능(count, mean, max 등).
- 단, mean 함수 사용 시 문자열 포함으로 인한 오류 안 나게 유의

In [32]:
# aggregate 사용해보기
sample.set_index(['airline', 'source_city']).groupby(['airline', 'source_city']).aggregate(['min', 'max', 'count']).head()

                      flight               departure_time              stops  \
                         min     max count            min    max count   min
airline source_city
AirAsia Bangalore    I5-1228  I5-996  3364      Afternoon  Night  3364   one
        Chennai      I5-1228  I5-821  1498      Afternoon  Night  1498   one
        Delhi        I5-1529  I5-881  4387      Afternoon  Night  4387   one
        Hyderabad    I5-1426  I5-974  1844      Afternoon  Night  1844   one
        Kolkata      I5-1563  I5-991  2829      Afternoon  Night  2829   one

                                arrival_time  ... class duration               \
                      max count          min  ... count      min    max count
airline source_city                           ...
AirAsia Bangalore    zero  3364    Afternoon  ...  3364     0.92  19.58  3364
        Chennai      zero  1498    Afternoon  ...  1498     0.92  17.83  1498
        Delhi        zero  4387    Afternoon  ...  4387     2.17  18.00  4387
        Hyderabad    zero  1844    Afternoon  ...  1844     0.92  15.33  1844
        Kolkata      zero  2829    Afternoon  ...  2829     2.08  18.33  2829

                    days_left           price
                          min max count   min    max count
airline source_city
AirAsia Bangalore           1  49  3364  1603  25993  3364
        Chennai             2  49  1498  1105  21364  1498
        Delhi               1  49  4387  1998  31917  4387
        Hyderabad           1  49  1844  1544  30211  1844
        Kolkata             1  49  2829  2436  26360  2829

[5 rows x 27 columns]

In [35]:
# 원하는 컬럼만 지정
sample.set_index(['airline', 'source_city'])[ ['duration', 'days_left', 'price'] ].groupby(['airline', 'source_city']).aggregate(['min', 'max', 'count']).head()

                    duration              days_left           price         \
                         min    max count       min max count   min    max
airline source_city
AirAsia Bangalore       0.92  19.58  3364         1  49  3364  1603  25993
        Chennai         0.92  17.83  1498         2  49  1498  1105  21364
        Delhi           2.17  18.00  4387         1  49  4387  1998  31917
        Hyderabad       0.92  15.33  1844         1  49  1844  1544  30211
        Kolkata         2.08  18.33  2829         1  49  2829  2436  26360


                    count
airline source_city
AirAsia Bangalore    3364
        Chennai      1498
        Delhi        4387
        Hyderabad    1844
        Kolkata      2829

## pivot_table
- DataFrame 형태를 변경
- 새로운 인사이트를 발견할 수 있음
- 새로운 데이터 생성 가능하므로 퓨처 엔지니어링에 활용 가능


```
pandas.pivot_table(data, index, columns, aggfunc)
# 예를 들면 이렇게
pd.pivot_table(data=sample, index='고객ID', columns='상품코드', values='구매금액', aggfunc='mean')
```

In [39]:
# 딕셔너리를 이용해서 dataframe 만들기

pivot_sample = pd.DataFrame({
    '고객ID': ['cust_1', 'cust_1', 'cust_1', 'cust_2', 'cust_2', 'cust_2', 'cust_3', 'cust_3', 'cust_3'],
    '상품코드': ['p1', 'p2', 'p3', 'p1', 'p2', 'p3', 'p1', 'p2', 'p3'],
    '등급': ['A', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'B'],
    '구매금액': [30, 10, 0, 40, 15, 30, 0, 0, 10],
    '나이': [15, 40, 33, 29, 6, 30, 54, 69, 38]
})

pivot_sample

     고객ID 상품코드 등급  구매금액  나이
0  cust_1   p1  A    30  15
1  cust_1   p2  A    10  40
2  cust_1   p3  A     0  33
3  cust_2   p1  A    40  29
4  cust_2   p2  A    15   6
5  cust_2   p3  A    30  30
6  cust_3   p1  B     0  54
7  cust_3   p2  B     0  69
8  cust_3   p3  B    10  38

In [41]:
pivot_sample.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   고객ID    9 non-null      object
 1   상품코드    9 non-null      object
 2   등급      9 non-null      object
 3   구매금액    9 non-null      int64
 4   나이      9 non-null      int64
dtypes: int64(2), object(3)
memory usage: 488.0+ bytes

### 2-1. pivot_table() 함수

- **index, columns에는 '범주형' 컬럼 지정해야 함!**

In [40]:
# pivot_table() 함수 사용해보기
# aggfunc 옵션의 디폴트는 mean이다. aggfunc 옵션이 없어도 결과는 똑같다.
# 하지만 상품코드와 등급 컬럼은 문자열이어서 평균을 구할 수 없어 에러 발생

pd.pivot_table( data=pivot_sample, index='고객ID', aggfunc='mean' )

TypeError: agg function failed [how->mean,dtype->object]

In [42]:
# 이럴 땐 이렇게 컬럼을 지정해놓고 수행!
pd.pivot_table( data=pivot_sample[ ['고객ID', '구매금액', '나이'] ], index='고객ID', aggfunc='mean' )

             구매금액         나이
고객ID
cust_1  13.333333  29.333333
cust_2  28.333333  21.666667
cust_3   3.333333  53.666667

In [43]:
# 피봇이랑 이렇게 그룹핑 하는거랑 결과는 동일한 것 확인
pivot_sample[['고객ID', '구매금액', '나이']].groupby('고객ID').mean()

             구매금액         나이
고객ID
cust_1  13.333333  29.333333
cust_2  28.333333  21.666667
cust_3   3.333333  53.666667

In [44]:
# 이번에는 columns 옵션도 넣고 실행해보기
pivot_sample.pivot_table(index='고객ID', columns='상품코드', aggfunc='sum')

       구매금액          나이         등급
상품코드     p1  p2  p3  p1  p2  p3 p1 p2 p3
고객ID
cust_1   30  10   0  15  40  33  A  A  A
cust_2   40  15  30  29   6  30  A  A  A
cust_3    0   0  10  54  69  38  B  B  B

In [45]:
# 이번에는 values 옵션도 넣고 실행해보기
pivot_sample.pivot_table(index='고객ID', columns='상품코드', values='구매금액', aggfunc='mean')

상품코드      p1    p2    p3
고객ID
cust_1  30.0  10.0   0.0
cust_2  40.0  15.0  30.0
cust_3   0.0   0.0  10.0

### 2-2. pivot_table의 추가 살펴 보기
- pivot_table은 aggregation 함수를 활용하여 처리

In [50]:
# 집계함수 옵션을 sum으로 하여 합계 구하기
pivot_sample.pivot_table(index='등급', columns='상품코드', values='구매금액', aggfunc='sum')

상품코드  p1  p2  p3
등급
A     70  25  30
B      0   0  10

In [53]:
# 위와 같은 결과를 얻기 위한 다른 코드
pd.pivot_table(data=pivot_sample, index='등급', columns='상품코드', values='구매금액', aggfunc=np.sum) #aggfunc='sum'도 됨

상품코드  p1  p2  p3
등급
A     70  25  30
B      0   0  10

## stack, unstack

### stack
- 컬럼 레벨로 보이는 컬럼명들을 인덱스 레벨로 가져와 DataFrame 변경

### unstack
- 인덱스 레벨에서 보이는 인덱스값을 컬럼 레벨로 가져와 DataFrame 변경