In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

# warning 경고 제거하기
import warnings
warnings.filterwarnings('ignore')

In [3]:
# 판다스 옵션을 사용해서 화면에 보기 좋게 하기
pd.set_option('display.max_columns', 999)
pd.set_option('display.float_format', '{:.2f}'.format)

In [32]:
%cd drive/MyDrive/Colab\ Notebooks/github_python_ML/KT_AICE/AICE_source

[Errno 2] No such file or directory: 'drive/MyDrive/Colab Notebooks/github_python_ML/KT_AICE/AICE_source'
/content/drive/MyDrive/Colab Notebooks/github_python_ML/KT_AICE/AICE_source

In [34]:
df = pd.read_csv("clv_data.csv")
df

,Unnamed: 0,id,age,gender,income,days_on_platform,city,purchases
0,0,0,NaN,Male,126895,14.00,San Francisco,0
1,1,1,NaN,Male,161474,14.00,Tokyo,0
2,2,2,24.00,Male,104723,34.00,London,1
3,3,3,29.00,Male,43791,28.00,London,2
4,4,4,18.00,Female,132181,26.00,London,2
...,...,...,...,...,...,...,...,...
4995,4995,4995,NaN,Female,212261,28.00,San Francisco,1
4996,4996,4996,NaN,Male,70228,12.00,San Francisco,0
4997,4997,4997,NaN,Male,64995,14.00,New York City,0
4998,4998,4998,NaN,Male,56144,4.00,New York City,2
4999,4999,4999,NaN,Female,110977,29.00,London,0

In [35]:
df.describe()

       Unnamed: 0      id     age    income  days_on_platform  purchases
count     5000.00 5000.00 2554.00   5000.00           4859.00    5000.00
mean      2499.50 2499.50   30.20  79593.34             24.39       1.10
std       1443.52 1443.52   12.13  60304.06             18.15       1.18
min          0.00    0.00   10.00      4.00              1.00       0.00
25%       1249.75 1249.75   19.00  32752.50             10.00       0.00
50%       2499.50 2499.50   30.00  65989.00             21.00       1.00
75%       3749.25 3749.25   41.00 115406.50             35.00       2.00
max       4999.00 4999.00   50.00 388572.00            111.00       6.00

In [36]:
df.info() #Non-Null Count 확인

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        5000 non-null   int64
 1   id                5000 non-null   int64
 2   age               2554 non-null   float64
 3   gender            5000 non-null   object
 4   income            5000 non-null   int64
 5   days_on_platform  4859 non-null   float64
 6   city              5000 non-null   object
 7   purchases         5000 non-null   int64
dtypes: float64(2), int64(4), object(2)
memory usage: 312.6+ KB

#데이터 전처리

- 데이터 탐색하기
- 결측치 처리하기
- 이상치 처리하기
- Feature Engineering

## 데이터 전처리 > 데이터 탐색하기
1. Sample 데이터 확인: head(), tail()
2. 통계적 특성 확인: describe()
3. Table 정보 확인: info()
    - col, row 몇 개로 구성되었는가?
    - Non-Null count
    - Dtype(문자형, 실수형 ...)

## 데이터 전처리 > 결측치 처리하기
1. N/A(Not Available)
2. Null
3. NaN(Not a Number)


---
- 결측치 처리 특징 1: 실무자 견해가 많이 반영됨
    - 같은 데이터도 실무자 의견에 따라 결과가 달라질 수도 있고, 임의대로 결측치 처리 시 분석결과가 매우 틀어질 수 있음
- 결측치 처리 특징 2: 시간이 많이 투자되어야 함
    - 데이터 현실을 반영한 결측치 처리가 되어야 정확한 데이터 분석 가능
- 결측치 처리 특징 3: 결측치 제거가 가장 쉬운 방법
    - 막대한 데이터 손실 가능
- 결측치 처리 특징4: 단순 대치 시
    - 데이터에서 편향(bias)이 생길 수 있음


---
- 제거하기:
    - Listwise(dropna()):
        - 결측치가 존재하는 전체 행(row) 삭제 / 일부 변수(col) 값이 존재하더라도 row 통째로 삭제
    - Pairwise(dropna(how='all')):
        - 모든 변수(col) 값이 결측치인 경우에만 해당 행(row) 삭제 / 남은 결측치는 데이터 분석 시 무시하게 됨
        - 데이터 손실을 최소화 하지만, 어쨋든 결측치를 포함하기 때문에 데이터 분석이나 최적 모델 만드는데 나쁜 영향을 주기도 함


---
- 채우기:
    - 값 대체하기:
        - 결측치를 평균화 값으로 대체 - 연속형 값일 경우 평균, 중앙값 | 범주형 값일 경우 최빈값으로 대체
    - 예측하기:
        - 결측치를 상관관계 등을 예측하여 대체
        - 결측치의 특성이 무작위로 관찰되는 것이 아니라고 가정, 상관관계나 예측모델을 사용해 채움
    - Pros/Cons:
        - Pros: 정보 손실 없이 결측치를 빠르게 채울 수 있음
        - Cons: 모든 결측치가 동일한 값을 가질 수 있음 -> 편향 가능
    - Methods:
        - fillna(): 지정한 값으로 값 채우기
        - interpolate(): 연속형 값에서 중간값으로 값 채우기 / 측값과 실측값 사이의 결측값을 마치 '그라데이션(gradation)' 기법으로 색깔을 조금씩 변화시켜가면서 부드럽게 채워나가는 방법